version: "2"

services:
  zookeeper:
    image: bobrik/zookeeper
    environment:
      ZK_CONFIG: tickTime=2000,initLimit=10,syncLimit=5,maxClientCnxns=128,forceSync=no,clientPort=2181
      ZK_ID: 1

  master:
    build: ./mesos-master-build
    image: mesos-demo/mesos-master:v1
    ports:
      - "5050:5050"
    environment:
      MESOS_ZK: zk://zookeeper:2181/mesos
      MESOS_QUORUM: 1
      MESOS_CLUSTER: localmesos
      MESOS_REGISTRY: replicated_log # default is in_memory for some reason
      MESOS_HOSTNAME: localhost
    depends_on:
      - zookeeper

  slave-one:
    build: ./mesos-slave-build
    image: mesos-demo/mesos-slave:v1
    ports:
      - "5051:5051"
    environment:
      MESOS_MASTER: zk://zookeeper:2181/mesos
      MESOS_CONTAINERIZERS: docker,mesos
      MESOS_PORT: 5051
      MESOS_RESOURCES: ports(*):[11000-11999]
      MESOS_HOSTNAME: localhost
      MESOS_WORK_DIR: /tmp/mesos
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /usr/local/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    command: --no-switch_user

  # slave-two:
  #   image: mesos-demo:mesos-slave
  #   ports:
  #     - "5052:5052"
  #   environment:
  #     MESOS_MASTER: zk://127.0.0.1:2181/mesos
  #     MESOS_CONTAINERIZERS: docker,mesos
  #     MESOS_PORT: 5052
  #     MESOS_RESOURCES: ports(*):[12000-12999]
  #     MESOS_HOSTNAME: localhost
  #     MESOS_WORK_DIR: /tmp/mesos
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup
  #     - /usr/local/bin/docker:/usr/bin/docker
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   depends_on:
  #     - zookeeper
  #   command: --no-switch_user

  marathon:
    image: mesosphere/marathon:v1.3.0
    ports:
      - "8090:8090"
    command: "--master zk://zookeeper:2181/mesos --zk zk://zookeeper:2181/marathon --http_port=8090 --webui_url http://localhost:8090"
    depends_on:
      - zookeeper

  chronos:
    image: mesosphere/chronos:chronos-2.4.0-0.1.20151007110204.ubuntu1404-mesos-0.24.1-0.2.35.ubuntu1404
    ports:
      - "8888:8888"
    command: "/usr/bin/chronos run_jar --http_port 8888 --master zk://zookeeper:2181/mesos --zk_hosts zk://zookeeper:2181/mesos --webui_url http://localhost:8888"
    depends_on:
      - zookeeper

  web:
    build: ./nginx-with-spark-build
    image: mesos-demo/nginx-with-spark:v1
    ports:
     - "8080:80"
  
  jupyter:
    image: jupyter/all-spark-notebook
    ports:
      - "8889:8888"
    command: "start.sh jupyter lab --NotebookApp.token=''"
